/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Point;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import controller.ControllerCadastroUsuarios;
import java.util.ArrayList;
import model.ModelCadastroUsuarios;
import model.ModelLogin;

/**
 *
 * @author Vinicius
 */
public class ViewLogin extends javax.swing.JFrame {

    ControllerCadastroUsuarios controllerCadastroUsuarios = new ControllerCadastroUsuarios();
    ModelCadastroUsuarios modelCadastroUsuarios = new ModelCadastroUsuarios();
    ModelLogin modelLogin = new ModelLogin();

    private Point point = new Point();

    /**
     * Creates new form TelaLogin
     */
    public ViewLogin() {
        initComponents();
    }

    public void textonulo() {
        Point p = this.getLocation();
        ViewLogin telaLogin = this;
        new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i < 4; i++) {
                        telaLogin.setLocation(p.x - 10, p.y - 2);
                        sleep(20);
                        telaLogin.setLocation(p.x + 10, p.y + 2);
                        sleep(20);
                    }
                    telaLogin.setLocation(p.x, p.y);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }.start();
    }

    private void entrar() {
        modelCadastroUsuarios.setUsuNome(JTextFieldHint.getText());
        modelCadastroUsuarios.setUsuSenha(JPassWordFieldHint.getText());

        if (JPassWordFieldHint.getText().equals("") || JPassWordFieldHint.getText().equals("")) {
            textonulo();
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos para se conectar.", "Notificação", JOptionPane.WARNING_MESSAGE);
        }

        if (JPassWordFieldHint.getText().equals("admin") && JPassWordFieldHint.getText().equals("admin")) {
            new ViewCadastroUsuario().setVisible(true);
        } else if (controllerCadastroUsuarios.getValidarUsuarioController(modelCadastroUsuarios)) {
            modelCadastroUsuarios = controllerCadastroUsuarios.getUsuarioController(JTextFieldHint.getText());
            modelLogin.cod_usu = modelCadastroUsuarios.getCpf();
            modelLogin.usuario = modelCadastroUsuarios.getUsuNome();
            new ViewPrincipal().setVisible(true);
            dispose();
        } else if (JPassWordFieldHint.getText().equals("") || JPassWordFieldHint.getText().equals("")) {
        } else {
            JOptionPane.showMessageDialog(this, "Usuário/Senha inválida.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonConectar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        JTextFieldHint = new controller.JTextFieldHint(new JTextField(),"user-icon", "Nome do usuário");  ;
        JPassWordFieldHint = new util.JPassWordFieldHint(new JTextField(),"padlock", "Senha");  ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 410));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 410));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(127, 177, 252));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login de Acesso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(91, 95, 99));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Entre com suas credenciais");

        buttonConectar.setBackground(new java.awt.Color(58, 65, 84));
        buttonConectar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonConectar.setForeground(new java.awt.Color(255, 255, 255));
        buttonConectar.setText("Conectar");
        buttonConectar.setBorderPainted(false);
        buttonConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonConectar.setFocusPainted(false);
        buttonConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonConectarMouseExited(evt);
            }
        });
        buttonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConectarActionPerformed(evt);
            }
        });
        buttonConectar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonConectarKeyPressed(evt);
            }
        });

        buttonSair.setBackground(new java.awt.Color(217, 81, 51));
        buttonSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSair.setForeground(new java.awt.Color(255, 255, 255));
        buttonSair.setText("Sair");
        buttonSair.setBorderPainted(false);
        buttonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSair.setFocusPainted(false);
        buttonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSairMouseExited(evt);
            }
        });
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        JTextFieldHint.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JTextFieldHint.setForeground(new java.awt.Color(102, 102, 102));
        JTextFieldHint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JTextFieldHintMouseExited(evt);
            }
        });
        JTextFieldHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldHintActionPerformed(evt);
            }
        });
        JTextFieldHint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextFieldHintKeyPressed(evt);
            }
        });

        JPassWordFieldHint.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JPassWordFieldHint.setForeground(new java.awt.Color(102, 102, 102));
        JPassWordFieldHint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPassWordFieldHintKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(JPassWordFieldHint, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldHint, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JPassWordFieldHint, JTextFieldHint, buttonConectar, buttonSair});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(JTextFieldHint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JPassWordFieldHint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(buttonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonConectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConectarMouseEntered
        buttonConectar.setBackground(new Color(110, 120, 149));
        buttonConectar.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonConectarMouseEntered

    private void buttonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConectarActionPerformed
        entrar();
    }//GEN-LAST:event_buttonConectarActionPerformed

    private void buttonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSairMouseEntered
        buttonSair.setBackground(new Color(242, 148, 125));
        buttonSair.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonSairMouseEntered

    private void buttonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSairMouseExited
        buttonSair.setBackground(new Color(217, 81, 51));
        buttonSair.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonSairMouseExited

    private void buttonConectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConectarMouseExited
        buttonConectar.setBackground(new Color(58, 65, 84));
        buttonConectar.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonConectarMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //COMANDO PARA MOVIMENTAR A TELA COM O MOUSE PRESCIONADO.
        //Point p = this.getLocation();
        //this.setLocation(p.x + evt.getX() - point.x,p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    private void JPassWordFieldHintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPassWordFieldHintKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entrar();
        }
    }//GEN-LAST:event_JPassWordFieldHintKeyPressed

    private void buttonConectarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonConectarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entrar();
        }
    }//GEN-LAST:event_buttonConectarKeyPressed

    private void JTextFieldHintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextFieldHintMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldHintMouseExited

    private void JTextFieldHintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextFieldHintKeyPressed

    }//GEN-LAST:event_JTextFieldHintKeyPressed

    private void JTextFieldHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldHintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldHintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JPassWordFieldHint;
    private javax.swing.JTextField JTextFieldHint;
    private javax.swing.JButton buttonConectar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
