/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.DAOEtapas;
import DAO.DAORecursos;
import conexoes.ConexaoMySql;
import controller.ControllerEtapas;
import controller.ControllerRecursos;
import java.awt.Color;
import java.awt.Point;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelEtapas;
import model.ModelRecursos;
import util.BLDatas;

/**
 *
 * @author Vinicius
 */
public class ViewRecursos extends javax.swing.JFrame {

    ControllerRecursos controllerRecursos = new ControllerRecursos();
    ModelRecursos modelRecursos = new ModelRecursos();
    List<ModelEtapas> lista_etapas = new ArrayList<>();
    List<ModelRecursos> listaModelRecursos = new ArrayList<>();
    Boolean condicao;
    String salvarAlterar;
    DAORecursos daoRecursos = new DAORecursos();
    ConexaoMySql c = new ConexaoMySql();
    int cod = 0;

    /**
     * Creates new form ViewEtapas
     */
    public ViewRecursos() {
        initComponents();
        habilitarDesabilitarCampos(false);
        carregarCadastros();
        salvarAlterar = "salvar";
        setLocationRelativeTo(null);
        jScrollPane2.getViewport().setBackground(Color.white);
        preencher_comboBoxEtapas();
        comboEtapaRef1.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldCodigo1 = new javax.swing.JTextField();
        fieldDescricao1 = new javax.swing.JTextField();
        comboEtapaRef1 = new componentes.UJComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaRecursos1 = new javax.swing.JTable();
        btnNovo1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        btnAlterar1 = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(642, 598));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel6.setText("Código:");

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel7.setText("Etapa do recurso:");

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setText("Descrição do recurso:");

        fieldCodigo1.setEnabled(false);
        fieldCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCodigo1ActionPerformed(evt);
            }
        });

        comboEtapaRef1.setAutocompletar(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(91, 95, 99));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Preencha as infmações abaixo para cadastrar uma nova etapa no sistema.");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 177, 252)));

        tabelaRecursos1.setAutoCreateRowSorter(true);
        tabelaRecursos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Etapa do recurso", "Descrição do recurso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRecursos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaRecursos1.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaRecursos1.setSelectionBackground(new java.awt.Color(127, 177, 252));
        tabelaRecursos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaRecursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaRecursos1);
        if (tabelaRecursos1.getColumnModel().getColumnCount() > 0) {
            tabelaRecursos1.getColumnModel().getColumn(0).setMinWidth(100);
            tabelaRecursos1.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaRecursos1.getColumnModel().getColumn(0).setMaxWidth(100);
            tabelaRecursos1.getColumnModel().getColumn(1).setMinWidth(190);
            tabelaRecursos1.getColumnModel().getColumn(1).setPreferredWidth(190);
            tabelaRecursos1.getColumnModel().getColumn(1).setMaxWidth(190);
        }

        btnNovo1.setBackground(new java.awt.Color(58, 65, 84));
        btnNovo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovo1.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo1.setText("Novo");
        btnNovo1.setBorderPainted(false);
        btnNovo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar1.setBackground(new java.awt.Color(58, 65, 84));
        btnSalvar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar1.setText("Salvar");
        btnSalvar1.setBorderPainted(false);
        btnSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar1.setBackground(new java.awt.Color(58, 65, 84));
        btnAlterar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar1.setText("Alterar");
        btnAlterar1.setBorderPainted(false);
        btnAlterar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir1.setBackground(new java.awt.Color(217, 81, 51));
        btnExcluir1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir1.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir1.setText("Excluir");
        btnExcluir1.setBorderPainted(false);
        btnExcluir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar1.setBackground(new java.awt.Color(217, 81, 51));
        btnVoltar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar1.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar1.setText("Voltar");
        btnVoltar1.setBorderPainted(false);
        btnVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboEtapaRef1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldDescricao1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboEtapaRef1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldDescricao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(127, 177, 252));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de recursos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 656, 621);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        ViewMenuCadastros tela = new ViewMenuCadastros();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        btnVoltar1.setBackground(new Color(217, 81, 51));
        btnVoltar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        btnVoltar1.setBackground(new Color(242, 148, 125));
        btnVoltar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // EXCLUI UM PRODUTO NO BANCO
        int linha = tabelaRecursos1.getSelectedRow();
        int codigoRecurso = (int) tabelaRecursos1.getValueAt(linha, 0);
        if (controllerRecursos.excluirCadastroRecursos(codigoRecurso)) {
            JOptionPane.showMessageDialog(this, "Recurso excluido com sucesso!", " ATENÇÃO", JOptionPane.WARNING_MESSAGE);;
            carregarCadastros();
            limparCampos();
            habilitarDesabilitarCampos(false);
            btnNovo1.setEnabled(false);
            btnAlterar1.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o Recurso!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        btnExcluir1.setBackground(new Color(217, 81, 51));
        btnExcluir1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        btnExcluir1.setBackground(new Color(242, 148, 125));
        btnExcluir1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        salvarAlterar = "alterar";
        btnAlterar1.setEnabled(false);
        btnNovo1.setEnabled(false);
        modelRecursos = new ModelRecursos();
        int linha = tabelaRecursos1.getSelectedRow();
        int codigo = 0;
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um recurso na tabela, antes de clicar em alterar!");
            limparCampos();
        } else {

            BLDatas bl = new BLDatas();

            codigo = (int) tabelaRecursos1.getValueAt(linha, 0);
            modelRecursos = controllerRecursos.retornarRecursosController(codigo);

            fieldCodigo1.setText(String.valueOf(modelRecursos.getIdRecurso()));
            comboEtapaRef1.setSelectedItem(modelRecursos.getTipoRecurso());
            fieldDescricao1.setText(modelRecursos.getDescricao());
        }

        habilitarDesabilitarCampos(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        btnAlterar1.setBackground(new Color(58, 65, 84));
        btnAlterar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        btnAlterar1.setBackground(new Color(110, 120, 149));
        btnAlterar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvar();
        carregarCadastros();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        btnSalvar1.setBackground(new Color(58, 65, 84));
        btnSalvar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        btnSalvar1.setBackground(new Color(110, 120, 149));
        btnSalvar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        salvarAlterar = "salvar";
        limparCampos();
        habilitarDesabilitarCampos(true);
        btnNovo1.setEnabled(false);
        btnAlterar1.setEnabled(false);
        btnExcluir1.setEnabled(false);
        buscaCodigoMaximo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        btnNovo1.setBackground(new Color(58, 65, 84));
        btnNovo1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        btnNovo1.setBackground(new Color(110, 120, 149));
        btnNovo1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnNovoMouseEntered

    private void tabelaRecursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaRecursosMouseClicked
        if (evt.getClickCount() == 2) {
            salvarAlterar = "alterar";
            btnAlterar1.setEnabled(false);
            btnNovo1.setEnabled(false);
            modelRecursos = new ModelRecursos();
            int linha = tabelaRecursos1.getSelectedRow();
            int codigo = 0;
            if (linha < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um recurso na tabela, antes de clicar em alterar!");
                limparCampos();
            } else {

                BLDatas bl = new BLDatas();

                codigo = (int) tabelaRecursos1.getValueAt(linha, 0);
                modelRecursos = controllerRecursos.retornarRecursosController(codigo);

                fieldCodigo1.setText(String.valueOf(modelRecursos.getIdRecurso()));
                comboEtapaRef1.setSelectedItem(modelRecursos.getTipoRecurso());
                fieldDescricao1.setText(modelRecursos.getDescricao());
            }

            habilitarDesabilitarCampos(true);
        }
    }//GEN-LAST:event_tabelaRecursosMouseClicked

    private void fieldCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCodigo1ActionPerformed

    public void preencher_comboBoxEtapas() {
        try {

            DAOEtapas daoEtapas = new DAOEtapas();
            lista_etapas = daoEtapas.busca();

            for (int i = 0; i < lista_etapas.size(); i++) {

                comboEtapaRef1.addItem(
                        String.valueOf(lista_etapas.get(i).getDescricao())
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na busca");
        }
    }

    public void salvar() {

        if (comboEtapaRef1.getSelectedIndex() == -1 || fieldDescricao1.getText().equals("")) {
            textonulo();
            JOptionPane.showMessageDialog(this, "Preencha todas informações para concluir o cadastro!");
            return;
        }

        modelRecursos.setTipoRecurso(comboEtapaRef1.getSelectedItem().toString());
        modelRecursos.setDescricao(fieldDescricao1.getText());

        if (salvarAlterar.equals("salvar")) {
            if (controllerRecursos.salvarCadastroRecursos(modelRecursos) >= 0) {
                JOptionPane.showMessageDialog(this, "Cadastro de recurso realizado com sucesso!", "Notificação", JOptionPane.WARNING_MESSAGE);
                limparCampos();
                habilitarDesabilitarCampos(false);
                btnNovo1.setEnabled(true);
                btnAlterar1.setEnabled(true);
                salvarAlterar = "salvar";
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o recurso!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            modelRecursos.setIdRecurso(Integer.parseInt(fieldCodigo1.getText()));
            if (controllerRecursos.atualizarRecursosController(modelRecursos)) {
                JOptionPane.showMessageDialog(this, "Recurso alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                habilitarDesabilitarCampos(false);
                btnNovo1.setEnabled(true);
                btnAlterar1.setEnabled(true);
                carregarCadastros();
                salvarAlterar = "alterar";
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar o recurso!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    public void textonulo() {
        Point p = this.getLocation();
        ViewRecursos telaRecurso = this;
        new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i < 4; i++) {
                        telaRecurso.setLocation(p.x - 10, p.y - 2);
                        sleep(20);
                        telaRecurso.setLocation(p.x + 10, p.y + 2);
                        sleep(20);
                    }
                    telaRecurso.setLocation(p.x, p.y);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }.start();
    }

    public void buscaCodigoMaximo() {
        DAORecursos daoRecursos = new DAORecursos();
        c.conectar();
        try {
            cod = daoRecursos.buscaCodigoMaximo();
        } catch (SQLException ex) {
            Logger.getLogger(ViewEtapas.class.getName()).log(Level.SEVERE, null, ex);
        }
        fieldCodigo1.setText(String.valueOf(cod + 1));
    }

    private void carregarCadastros() {
        listaModelRecursos = controllerRecursos.getListaRecursos();

        DefaultTableModel modelo = (DefaultTableModel) tabelaRecursos1.getModel();
        modelo.setNumRows(0);
        //inserir produtos na tabela
        int cont = listaModelRecursos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelRecursos.get(i).getIdRecurso(),
                listaModelRecursos.get(i).getTipoRecurso(),
                listaModelRecursos.get(i).getDescricao()
            });
        }
    }

    public void limparCampos() {
        fieldCodigo1.setText("");
        comboEtapaRef1.setSelectedIndex(-1);
        fieldDescricao1.setText("");
    }

    public void habilitarDesabilitarCampos(boolean condicao) {
        comboEtapaRef1.setEnabled(condicao);
        fieldDescricao1.setEnabled(condicao);
        btnSalvar1.setEnabled(condicao);
        btnExcluir1.setEnabled(condicao);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRecursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar1;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnVoltar1;
    private componentes.UJComboBox comboEtapaRef1;
    private javax.swing.JTextField fieldCodigo1;
    private javax.swing.JTextField fieldDescricao1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaRecursos1;
    // End of variables declaration//GEN-END:variables
}
