/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.DAOCadastroGeral;
import DAO.DAOCadastroUsuarios;
import DAO.DAOEtapas;
import DAO.DAOPerdas;
import DAO.DAOProdutos;
import DAO.DAORecursos;
import conexoes.ConexaoMySql;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ModelCadastroGeral;
import model.ModelCadastroUsuarios;
import model.ModelEtapas;
import model.ModelProdutos;
import model.ModelRecursos;
import util.BLDatas;
import controller.ControllerPerdas;
import java.awt.Point;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.ModelPerdas;
import model.ModelProducao;
import util.BLMascaras;

public class ViewPerdas extends javax.swing.JFrame {

    List<ModelProdutos> lista_produtos = new ArrayList<>();
    List<ModelEtapas> lista_etapas = new ArrayList<>();
    List<ModelRecursos> lista_recursos = new ArrayList<>();
    List<ModelCadastroGeral> lista_motivos = new ArrayList<>();
    List<ModelCadastroUsuarios> lista_usuarios = new ArrayList<>();
    ControllerPerdas controllerPerdas = new ControllerPerdas();
    DAOPerdas daoPerdas = new DAOPerdas();
    ModelPerdas modelPerdas = new ModelPerdas();
    ConexaoMySql c = new ConexaoMySql();
    int cod = 0, codP = 0;
    Boolean condicao;
    String salvarAlterar = "salvar";
    ViewConsulta viewConsulta;
    boolean todos = false;

    /**
     * Creates new form perdas
     */
    public ViewPerdas() {
        initComponents();
        preencher_comboBoxEtapas();
        preencher_comboBoxProduto();
        preencher_comboBoxRecurso();
        preencher_comboBoxMotivo();
        preencher_comboBoxOperador();
        buscaCodigoMaximo();
        limpaTela();
        salvarAlterar = "salvar";
        setLocationRelativeTo(null);
        habilitarDesabilitarCampos(false);
    }

    public ViewPerdas(ModelPerdas modelPerdas, ViewConsulta viewConsulta, boolean todos, int codPerdas) {
        initComponents();
        preencher_comboBoxEtapas();
        preencher_comboBoxProduto();
        preencher_comboBoxRecurso();
        preencher_comboBoxMotivo();
        preencher_comboBoxOperador();
        buscaCodigoMaximo();
        limpaTela();
        salvarAlterar = "salvar";
        setLocationRelativeTo(null);
        habilitarDesabilitarCampos(true);
        this.viewConsulta = viewConsulta;
        this.todos = todos;
        this.codP = codPerdas;

        BLDatas bl = new BLDatas();

        salvarAlterar = "alterar";

        fieldCodigo.setText(String.valueOf(modelPerdas.getIdCodigo()));
        comboProduto.setSelectedItem(modelPerdas.getDescProduto());
        comboEtapa.setSelectedItem(modelPerdas.getDescEtapa());
        comboRecurso.setSelectedItem(modelPerdas.getDescRecurso());
        try {
            dataPerdas.setText(bl.converterDataUSParaDateString(modelPerdas.getDataPerda()));
        } catch (Exception ex) {
            Logger.getLogger(ViewPerdas.class.getName()).log(Level.SEVERE, null, ex);
        }
        horaPerdas.setText(modelPerdas.getHoraPerda().toString());
        comboMotivo.setSelectedItem(modelPerdas.getMotivo());
        fieldPeso.setText(String.valueOf(modelPerdas.getPesoPerda()));
        comboOperador.setSelectedItem(modelPerdas.getOperador());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboProduto = new componentes.UJComboBox();
        comboEtapa = new componentes.UJComboBox();
        comboRecurso = new componentes.UJComboBox();
        comboOperador = new componentes.UJComboBox();
        comboMotivo = new componentes.UJComboBox();
        jLabel9 = new javax.swing.JLabel();
        fieldCodigo = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        dataPerdas = new javax.swing.JFormattedTextField();
        horaPerdas = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(127, 177, 252));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apontamento de Perdas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Produto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Etapa:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Recurso:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Data e hora perda:");

        fieldPeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Motivo da Perda:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Peso:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Operador:");

        comboProduto.setAutocompletar(true);

        comboEtapa.setAutocompletar(true);
        comboEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEtapaActionPerformed(evt);
            }
        });

        comboRecurso.setAutocompletar(true);

        comboOperador.setAutocompletar(true);

        comboMotivo.setAutocompletar(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Código:");

        fieldCodigo.setEnabled(false);

        btnNovo.setBackground(new java.awt.Color(58, 65, 84));
        btnNovo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setBorderPainted(false);
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(58, 65, 84));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorderPainted(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(217, 81, 51));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(217, 81, 51));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        dataPerdas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        horaPerdas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboOperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboEtapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboRecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldPeso)
                            .addComponent(fieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dataPerdas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horaPerdas))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataPerdas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(horaPerdas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carrega o banco de dados os produtos cadastrados no sistema
     */
    public void preencher_comboBoxProduto() {
        try {

            DAOProdutos daoProdutos = new DAOProdutos();
            lista_produtos = daoProdutos.busca();

            for (int i = 0; i < lista_produtos.size(); i++) {

                comboProduto.addItem(
                        String.valueOf(lista_produtos.get(i).getDescricao())
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na busca");
        }
    }

    /**
     * Carrega no banco de dados as etapas cadastradas no sistema
     */
    public void preencher_comboBoxEtapas() {
        try {

            DAOEtapas daoEtapas = new DAOEtapas();
            lista_etapas = daoEtapas.busca();

            for (int i = 0; i < lista_etapas.size(); i++) {

                comboEtapa.addItem(
                        String.valueOf(lista_etapas.get(i).getDescricao())
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na busca");
        }
    }

    /**
     * Carrega no banco de dados os recursos cadastrados no sistema
     */
    public void preencher_comboBoxRecurso() {
        try {

            DAORecursos daoRecursos = new DAORecursos();
            lista_recursos = daoRecursos.busca();

            for (int i = 0; i < lista_recursos.size(); i++) {

                comboRecurso.addItem(
                        String.valueOf(lista_recursos.get(i).getDescricao())
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na busca");
        }
    }

    /**
     * Carrega no banco de dados os motivos cadastrados no sistema
     */
    public void preencher_comboBoxMotivo() {
        try {

            DAOCadastroGeral daoCadastroGeral = new DAOCadastroGeral();
            lista_motivos = daoCadastroGeral.buscaPerdas();

            for (int i = 0; i < lista_motivos.size(); i++) {

                comboMotivo.addItem(
                        String.valueOf(lista_motivos.get(i).getDescricao())
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na busca");
        }
    }

    /**
     * Carrega no banco de dados os operadores cadastrados no sistema
     */
    public void preencher_comboBoxOperador() {
        try {

            DAOCadastroUsuarios daoCadastroUsuarios = new DAOCadastroUsuarios();
            lista_usuarios = daoCadastroUsuarios.busca();

            for (int i = 0; i < lista_usuarios.size(); i++) {

                comboOperador.addItem(
                        String.valueOf(lista_usuarios.get(i).getNome())
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na busca");
        }
    }

    /**
     * Função para salvar os lançamentos realizados
     */
    public void salvar() {

        BLDatas bl = new BLDatas();
        BLMascaras con = new BLMascaras();

        modelPerdas.setDescProduto(String.valueOf(comboProduto.getSelectedItem()));
        modelPerdas.setDescEtapa(String.valueOf(comboEtapa.getSelectedItem()));
        modelPerdas.setDescRecurso(String.valueOf(comboRecurso.getSelectedItem()));
        try {
            modelPerdas.setDataPerda(bl.converterDataParaDateUS(bl.converterDataStringParaDate(dataPerdas.getText())));
        } catch (Exception ex) {
            Logger.getLogger(ViewPerdas.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelPerdas.setMotivo(String.valueOf(comboMotivo.getSelectedItem()));
        modelPerdas.setPesoPerda(Double.parseDouble(con.converterVirgulaParaPonto(fieldPeso.getText())));
        modelPerdas.setOperador(String.valueOf(comboOperador.getSelectedItem()));
        try {
            SimpleDateFormat horaMinutos = new SimpleDateFormat("HH:mm");
            Date data = horaMinutos.parse(horaPerdas.getText());
            Time time = new Time(data.getTime());
            modelPerdas.setHoraPerda(time);
        } catch (ParseException ex) {
            Logger.getLogger(ViewPerdas.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (salvarAlterar.equals("salvar")) {
            if (controllerPerdas.salvarCadastroPerdas(modelPerdas) > 0) {
                JOptionPane.showMessageDialog(this, "Perda cadastrada com sucesso!", "Notificação", JOptionPane.WARNING_MESSAGE);
                buscaCodigoMaximo();
                limpaTela();
                habilitarDesabilitarCampos(false);
                btnNovo.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar a perda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            modelPerdas.setIdCodigo(Integer.parseInt(fieldCodigo.getText()));
            if (controllerPerdas.atualizarPerdasController(modelPerdas)) {
                JOptionPane.showMessageDialog(this, "Perda alterada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limpaTela();
                //habilitarDesabilitarCampos(false);
                btnNovo.setEnabled(true);
                salvarAlterar = "alterar";
                dispose();
                if (this.todos == true) {
                    viewConsulta.carregarTodos();
                } else {
                    viewConsulta.carregarPerdas(!todos);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar a perda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    public void buscaCodigoMaximo() {
        DAOPerdas daoPerdas = new DAOPerdas();
        c.conectar();
        try {
            cod = daoPerdas.buscaCodigoMaximo();
        } catch (SQLException ex) {
            Logger.getLogger(ViewEtapas.class.getName()).log(Level.SEVERE, null, ex);
        }
        fieldCodigo.setText(String.valueOf(cod + 1));
    }

    /**
     * Função para limpar a tela após salvar o lançamento
     */
    public void limpaTela() {
        fieldCodigo.setText("");
        comboProduto.setSelectedIndex(-1);
        comboEtapa.setSelectedIndex(-1);
        comboRecurso.setSelectedIndex(-1);
        dataPerdas.setText("");
        horaPerdas.setText("");
        comboMotivo.setSelectedIndex(-1);
        fieldPeso.setText("");
        comboOperador.setSelectedIndex(-1);
    }

    public void habilitarDesabilitarCampos(boolean condicao) {
        comboProduto.setEnabled(condicao);
        comboEtapa.setEnabled(condicao);
        comboRecurso.setEnabled(condicao);
        dataPerdas.setEnabled(condicao);
        horaPerdas.setEnabled(condicao);
        comboMotivo.setEnabled(condicao);
        fieldPeso.setEnabled(condicao);
        comboOperador.setEnabled(condicao);
        btnSalvar.setEnabled(condicao);
        btnExcluir.setEnabled(condicao);
    }

    public void textonulo() {
        Point p = this.getLocation();
        ViewPerdas telaPerdas = this;
        new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i < 4; i++) {
                        telaPerdas.setLocation(p.x - 10, p.y - 2);
                        sleep(20);
                        telaPerdas.setLocation(p.x + 10, p.y + 2);
                        sleep(20);
                    }
                    telaPerdas.setLocation(p.x, p.y);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }.start();
    }

    public void validacao() {
        if (comboProduto.getSelectedIndex() == -1 || comboEtapa.getSelectedIndex() == -1 || comboRecurso.getSelectedIndex() == -1
                || dataPerdas.getText().equals("") || horaPerdas.getText().equals("") || fieldPeso.getText().equals("") 
                || comboMotivo.getSelectedIndex() == -1 || comboOperador.getSelectedIndex() == -1) {
            textonulo();
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para realizar o cadastro.");
        } else {
            salvar();
        }
    }


    private void comboEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEtapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEtapaActionPerformed

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        btnNovo.setBackground(new Color(110, 120, 149));
        btnNovo.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnNovoMouseEntered

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        btnNovo.setBackground(new Color(58, 65, 84));
        btnNovo.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        salvarAlterar = "salvar";
        limpaTela();
        habilitarDesabilitarCampos(true);
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        buscaCodigoMaximo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        btnSalvar.setBackground(new Color(110, 120, 149));
        btnSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        btnSalvar.setBackground(new Color(58, 65, 84));
        btnSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        validacao();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        btnExcluir.setBackground(new Color(242, 148, 125));
        btnExcluir.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        btnExcluir.setBackground(new Color(217, 81, 51));
        btnExcluir.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // EXCLUI UMA PARADA NO BANCO
        if (controllerPerdas.excluirCadastroPerdas(codP)) {
            JOptionPane.showMessageDialog(this, "Perda excluida com sucesso!", " ATENÇÃO", JOptionPane.WARNING_MESSAGE);;
            limpaTela();
            btnNovo.setEnabled(false);
            dispose();
            if (this.todos == true) {
                viewConsulta.carregarTodos();
            } else {
                viewConsulta.carregarPerdas(!todos);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir a perda!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        btnVoltar.setBackground(new Color(242, 148, 125));
        btnVoltar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        btnVoltar.setBackground(new Color(217, 81, 51));
        btnVoltar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        ViewPrincipal tela = new ViewPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPerdas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPerdas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPerdas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPerdas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPerdas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private componentes.UJComboBox comboEtapa;
    private componentes.UJComboBox comboMotivo;
    private componentes.UJComboBox comboOperador;
    private componentes.UJComboBox comboProduto;
    private componentes.UJComboBox comboRecurso;
    private javax.swing.JFormattedTextField dataPerdas;
    private javax.swing.JTextField fieldCodigo;
    private javax.swing.JTextField fieldPeso;
    private javax.swing.JFormattedTextField horaPerdas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
