/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.DAOCadastroGeral;
import conexoes.ConexaoMySql;
import controller.ControllerCadastroGeral;
import java.awt.Color;
import java.awt.Point;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCadastroGeral;

/**
 *
 * @author Vinicius
 */
public class ViewCadastro extends javax.swing.JFrame {

    ControllerCadastroGeral controllerCadastroGeral = new ControllerCadastroGeral();
    ModelCadastroGeral modelCadastroGeral = new ModelCadastroGeral();
    ArrayList<ModelCadastroGeral> listaModelCadastroGeral = new ArrayList<>();
    DAOCadastroGeral daoCadastroGeral = new DAOCadastroGeral();
    String salvarAlterar;
    ConexaoMySql c = new ConexaoMySql();
    int cod = 0;

    /**
     * Creates new form cadastro
     */
    public ViewCadastro() {
        initComponents();
        habilitarDesabilitarCampos(false);
        carregarCadastros();
        salvarAlterar = "salvar";
        setLocationRelativeTo(null);
        jComboBox1.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //CODIGOS
    public void salvar() {

        if (jComboBox1.getSelectedIndex() == -1 || fieldDescricao.getText().equals("")) {
            textonulo();
            JOptionPane.showMessageDialog(this, "Preencha todas informações para concluir o cadastro!");
            return;
        }

        modelCadastroGeral = new ModelCadastroGeral();
        modelCadastroGeral.setTipoCadastro(jComboBox1.getSelectedItem().toString());
        modelCadastroGeral.setDescricao(fieldDescricao.getText());

        if (salvarAlterar.equals("salvar")) {
            if (controllerCadastroGeral.salvarCadastroGeralController(modelCadastroGeral) > 0) {
                JOptionPane.showMessageDialog(this, "Cadastro cadastro com sucesso!", "Notificação", JOptionPane.WARNING_MESSAGE);
                limparCampos();
                habilitarDesabilitarCampos(false);
                salvarAlterar = "salvar";
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o cadastro!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            modelCadastroGeral.setIdCadastro(Integer.parseInt(fieldCodigo.getText()));
            if (controllerCadastroGeral.atualizarCadastroGeralController(modelCadastroGeral)) {
                JOptionPane.showMessageDialog(this, "Cadastro alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                carregarCadastros();
                salvarAlterar = "salvar";
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar o cadastro!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void carregarCadastros() {
        listaModelCadastroGeral = controllerCadastroGeral.retornarListaParadasController();

        DefaultTableModel modelo = (DefaultTableModel) listaCadastros.getModel();
        modelo.setNumRows(0);
        //inserir produtos na tabela
        int cont = listaModelCadastroGeral.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelCadastroGeral.get(i).getIdCadastro(),
                listaModelCadastroGeral.get(i).getTipoCadastro(),
                listaModelCadastroGeral.get(i).getDescricao()
            });
        }
    }

    public void buscaCodigoMaximo() {
        DAOCadastroGeral daoCadastroGeral = new DAOCadastroGeral();
        c.conectar();
        try {
            cod = daoCadastroGeral.buscaCodigoMaximo();
        } catch (SQLException ex) {
            Logger.getLogger(ViewEtapas.class.getName()).log(Level.SEVERE, null, ex);
        }
        fieldCodigo.setText(String.valueOf(cod + 1));
    }

    public void limparCampos() {
        fieldCodigo.setText("");
        jComboBox1.setSelectedIndex(-1);
        fieldDescricao.setText("");
    }

    public void habilitarDesabilitarCampos(boolean condicao) {
        jComboBox1.setEnabled(condicao);
        fieldDescricao.setEnabled(condicao);
        cadastroSalvar.setEnabled(condicao);
        btnExcluir.setEnabled(condicao);
    }

    public void habilitarDesabilitarCamposAlterarExcluir(boolean condicao) {
        jComboBox1.setEnabled(condicao);
        fieldDescricao.setEnabled(condicao);
        btnAlterar.setEnabled(false);
    }

    public void textonulo() {
        Point p = this.getLocation();
        ViewCadastro telaCadastro = this;
        new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i < 4; i++) {
                        telaCadastro.setLocation(p.x - 10, p.y - 2);
                        sleep(20);
                        telaCadastro.setLocation(p.x + 10, p.y + 2);
                        sleep(20);
                    }
                    telaCadastro.setLocation(p.x, p.y);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }.start();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldDescricao = new javax.swing.JTextField();
        cadastroNovo = new javax.swing.JButton();
        cadastroSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jComboBox1 = new componentes.UJComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCadastros = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 540));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(127, 177, 252));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastros Gerais");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 177, 252)));
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tipo de cadastro:");

        fieldCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldCodigo.setEnabled(false);
        fieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCodigoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Descrição:");

        fieldDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cadastroNovo.setBackground(new java.awt.Color(58, 65, 84));
        cadastroNovo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastroNovo.setForeground(new java.awt.Color(255, 255, 255));
        cadastroNovo.setText("Novo");
        cadastroNovo.setBorderPainted(false);
        cadastroNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastroNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastroNovoMouseExited(evt);
            }
        });
        cadastroNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroNovoActionPerformed(evt);
            }
        });

        cadastroSalvar.setBackground(new java.awt.Color(58, 65, 84));
        cadastroSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastroSalvar.setForeground(new java.awt.Color(255, 255, 255));
        cadastroSalvar.setText("Salvar");
        cadastroSalvar.setBorderPainted(false);
        cadastroSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastroSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastroSalvarMouseExited(evt);
            }
        });
        cadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(217, 81, 51));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Motivo de parada", "Motivo de perda" }));
        jComboBox1.setAutocompletar(true);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 177, 252)));

        listaCadastros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Motivo", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaCadastros.setGridColor(new java.awt.Color(255, 255, 255));
        listaCadastros.setSelectionBackground(new java.awt.Color(127, 177, 252));
        listaCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCadastrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaCadastros);
        if (listaCadastros.getColumnModel().getColumnCount() > 0) {
            listaCadastros.getColumnModel().getColumn(0).setMinWidth(60);
            listaCadastros.getColumnModel().getColumn(0).setPreferredWidth(60);
            listaCadastros.getColumnModel().getColumn(0).setMaxWidth(60);
            listaCadastros.getColumnModel().getColumn(1).setMinWidth(160);
            listaCadastros.getColumnModel().getColumn(1).setPreferredWidth(160);
            listaCadastros.getColumnModel().getColumn(1).setMaxWidth(160);
        }

        btnExcluir.setBackground(new java.awt.Color(217, 81, 51));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(58, 65, 84));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setFocusable(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldCodigo)
                            .addComponent(fieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cadastroNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(cadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroNovoMouseEntered
        cadastroNovo.setBackground(new Color(110, 120, 149));
        cadastroNovo.setForeground(Color.WHITE);
    }//GEN-LAST:event_cadastroNovoMouseEntered

    private void cadastroNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroNovoMouseExited
        cadastroNovo.setBackground(new Color(58, 65, 84));
        cadastroNovo.setForeground(Color.WHITE);
    }//GEN-LAST:event_cadastroNovoMouseExited

    private void cadastroSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroSalvarMouseEntered
        cadastroSalvar.setBackground(new Color(110, 120, 149));
        cadastroSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_cadastroSalvarMouseEntered

    private void cadastroSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroSalvarMouseExited
        cadastroSalvar.setBackground(new Color(58, 65, 84));
        cadastroSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_cadastroSalvarMouseExited

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        btnVoltar.setBackground(new Color(242, 148, 125));
        btnVoltar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        btnVoltar.setBackground(new Color(217, 81, 51));
        btnVoltar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        ViewMenuCadastros tela = new ViewMenuCadastros();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void fieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCodigoActionPerformed

    private void cadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroSalvarActionPerformed
        salvar();
        carregarCadastros();
    }//GEN-LAST:event_cadastroSalvarActionPerformed

    private void cadastroNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroNovoActionPerformed
        salvarAlterar = "salvar";
        limparCampos();
        habilitarDesabilitarCampos(true);
        buscaCodigoMaximo();
    }//GEN-LAST:event_cadastroNovoActionPerformed

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        btnExcluir.setBackground(new Color(242, 148, 125));
        btnExcluir.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        btnExcluir.setBackground(new Color(217, 81, 51));
        btnExcluir.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // EXCLUI UM PRODUTO NO BANCO 
        int linha = listaCadastros.getSelectedRow();
        int codigoCadastro = (int) listaCadastros.getValueAt(linha, 0);
        if (controllerCadastroGeral.excluirCadastroGeralController(codigoCadastro)) {
            JOptionPane.showMessageDialog(this, "Cadastro excluido com sucesso!", " ATENÇÃO", JOptionPane.WARNING_MESSAGE);;
            carregarCadastros();
            limparCampos();
            habilitarDesabilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o cadastro!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        btnAlterar.setBackground(new Color(110, 120, 149));
        btnAlterar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        btnAlterar.setBackground(new Color(58, 65, 84));
        btnAlterar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        salvarAlterar = "altear";
        modelCadastroGeral = new ModelCadastroGeral();
        int linha = listaCadastros.getSelectedRow();
        int codigo = 0;
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela, antes de clicar em alterar!");
        } else {
            codigo = (int) listaCadastros.getValueAt(linha, 0);
            modelCadastroGeral = controllerCadastroGeral.retornarCadastroGeralController(codigo);
        }

        fieldCodigo.setText(String.valueOf(modelCadastroGeral.getIdCadastro()));
        jComboBox1.setSelectedItem(modelCadastroGeral.getTipoCadastro());
        fieldDescricao.setText(String.valueOf(modelCadastroGeral.getDescricao()));

        habilitarDesabilitarCampos(true);

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void listaCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCadastrosMouseClicked
        if (evt.getClickCount() == 2) {
            salvarAlterar = "altear";
            modelCadastroGeral = new ModelCadastroGeral();
            int linha = listaCadastros.getSelectedRow();
            int codigo = 0;
            if (linha < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um produto na tabela, antes de clicar em alterar!");
            } else {
                codigo = (int) listaCadastros.getValueAt(linha, 0);
                modelCadastroGeral = controllerCadastroGeral.retornarCadastroGeralController(codigo);
            }

            fieldCodigo.setText(String.valueOf(modelCadastroGeral.getIdCadastro()));
            jComboBox1.setSelectedItem(modelCadastroGeral.getTipoCadastro());
            fieldDescricao.setText(String.valueOf(modelCadastroGeral.getDescricao()));

            habilitarDesabilitarCampos(true);
        }
    }//GEN-LAST:event_listaCadastrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastro().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton cadastroNovo;
    private javax.swing.JButton cadastroSalvar;
    private javax.swing.JTextField fieldCodigo;
    private javax.swing.JTextField fieldDescricao;
    private componentes.UJComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listaCadastros;
    // End of variables declaration//GEN-END:variables
}
